export enum USER_ROLE {
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  PARTNER = "PARTNER",
  CUSTOMER = "CUSTOMER",
  PUBLIC = "PUBLIC",
  AUTHENTICATED = "AUTHENTICATED",
  NONE = "NONE"
}

export enum LOAN_PRODUCT {
  HOME_LOAN = "HOME_LOAN",
  LAP = "LAP",
  PERSONAL_LOAN = "PERSONAL_LOAN",
  WORKING_CAPITAL = "WORKING_CAPITAL",
  CREDIT_CARD = "CREDIT_CARD"
}

export enum APPLICATION_STATUS {
  CREATED = "CREATED",
  PENDING_DOCUMENTS = "PENDING_DOCUMENTS",
  UNDER_REVIEW = "UNDER_REVIEW",
  PARTNER_ASSIGNED = "PARTNER_ASSIGNED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  DISBURSED = "DISBURSED"
}

export enum EMPLOYMENT_TYPE {
  SALARIED = "SALARIED",
  SELF_EMPLOYED_PROFESSIONAL = "SELF_EMPLOYED_PROFESSIONAL",
  SELF_EMPLOYED_BUSINESS = "SELF_EMPLOYED_BUSINESS"
}

export enum DOCUMENT_TYPE {
  PAN = "PAN",
  AADHAAR = "AADHAAR",
  SALARY_SLIP = "SALARY_SLIP",
  BANK_STATEMENT = "BANK_STATEMENT",
  ITR = "ITR",
  GST_RETURN = "GST_RETURN",
  PROPERTY_DOCUMENT = "PROPERTY_DOCUMENT"
}
